name: shift_handover_challenge
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  shift_handover_api:
    path: packages/shift_handover_api
  shift_handover_repository:
    path: packages/shift_handover_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
